version: '3.8'

services:
  postgres:
    container_name: user-app-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aba32835

  user-app:
    container_name: user-app
    image: management-app-jpa
    ports:
      - "8083:8082"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Aba32835
      SPRING_APPLICATION_NAME: user-app
      SERVER_PORT: 8080

    network_mode: "host"
    tty: true
    stdin_open: true